// <auto-generated />
using System;
using ConsoleApp2.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(GoodsContext))]
    [Migration("20230309070343_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("ConsoleApp2.DB.Category", b =>
                {
                    b.Property<Guid>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = new Guid("cec11f6b-1a28-4981-8042-66780bb94c1f"),
                            Name = "Овощи"
                        },
                        new
                        {
                            IdCategory = new Guid("2acee48d-73fd-42f9-97a9-3065f135d683"),
                            Name = "Фрукты"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.DB.Good", b =>
                {
                    b.Property<Guid>("IDGood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryIdCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Sale")
                        .HasColumnType("REAL");

                    b.HasKey("IDGood");

                    b.HasIndex("CategoryIdCategory");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("ConsoleApp2.DB.Good", b =>
                {
                    b.HasOne("ConsoleApp2.DB.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryIdCategory");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
